const wsType = {
  AUTHORIZATION: "AUTHORIZATION",
  OPERATOR_LOCATION_ADD: "OPERATOR_LOCATION_ADD",
  BUSINESS_ADD: "BUSINESS_ADD",
  BUSINESS_UPDATE: "BUSINESS_UPDATE",
  OPERATOR_ENTER_BUSINESS: "OPERATOR_ENTER_BUSINESS",
  OPERATOR_LEAVE_BUSINESS: "OPERATOR_LEAVE_BUSINESS",
  INVOICE_ADD: "INVOICE_ADD",
  INVOICE_UPDATE: "INVOICE_UPDATE",
};

module.exports = wsType;
