const wsType = {
  INTRODUCTION: "INTRODUCTION",
  USER_LOCATION_ADD: "USER_LOCATION_ADD",
  BUSINESS_ADD: "BUSINESS_ADD",
  BUSINESS_UPDATE: "BUSINESS_UPDATE",
  WORKER_ENTER_BUSINESS: "WORKER_ENTER_BUSINESS",
  WORKER_LEAVE_BUSINESS: "WORKER_LEAVE_BUSINESS",
  INVOICE_ADD: "INVOICE_ADD",
  INVOICE_UPDATE: "INVOICE_UPDATE",
};

module.exports = wsType;
