const wsType = {
  BUSINESS_ADD: "BUSINESS_ADD",
  WORKER_ENTER_BUSINESS: "WORKER_ENTER_BUSINESS",
  WORKER_LEAVE_BUSINESS: "WORKER_LEAVE_BUSINESS",
  INVOICE_ADD: "INVOICE_ADD",
};

exports.wsType = wsType;
