const wsType = {
  AUTHORIZATION: "AUTHORIZATION",
  TASK_ADD: "TASK_ADD",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_DELETE: "TASK_DELETE",
  OPERATOR_LOCATION_ADD: "OPERATOR_LOCATION_ADD",
  OPERATOR_ENTER_TASK: "OPERATOR_ENTER_TASK",
  OPERATOR_LEAVE_TASK: "OPERATOR_LEAVE_TASK",
  OPERATOR_ADD: "OPERATOR_ADD",
  OPERATOR_REMOVE: "OPERATOR_REMOVE",
  INVOICE_ADD: "INVOICE_ADD",
  INVOICE_UPDATE: "INVOICE_UPDATE",
};

module.exports = wsType;
