const wsType = {
  AUTHORIZATION: "AUTHORIZATION",
  TASK_ADD: "TASK_ADD",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_DELETE: "TASK_DELETE",
  OPERATOR_LOCATION_ADD: "OPERATOR_LOCATION_ADD",
  OPERATOR_ENTER_NOTIFICATION: "OPERATOR_ENTER_NOTIFICATION",
  OPERATOR_LEAVE_NOTIFICATION: "OPERATOR_LEAVE_NOTIFICATION",
  TASK_ADD_NOTIFICATION: "TASK_ADD_NOTIFICATION",
  INVOICE_ADD_NOTIFICATION: "INVOICE_ADD_NOTIFICATION",
  INVOICE_UPDATE_NOTIFICATION: "INVOICE_UPDATE_NOTIFICATION",
  OPERATOR_ADD: "OPERATOR_ADD",
  ADMIN_ADD: "ADMIN_ADD",
  OPERATOR_REMOVE: "OPERATOR_REMOVE",
  ADMIN_REMOVE: "ADMIN_REMOVE",
  INVOICE_ADD: "INVOICE_ADD",
  INVOICE_UPDATE: "INVOICE_UPDATE",
};

module.exports = wsType;
